---
title: "Compare DEGs"
author: "Kennedi Todd"
date: "2023-08-30"
output: html_document
---

# Setup
```{r}
library(ComplexUpset) # intersection_size()
library(ggplot2)      # scale_y_continuous()
library(UpSetR)       # fromList()
```

# Read tables
```{r}
thresh <- 0.05

group_sex_GFAP <- read.table(
  "../../results/meninges_1CPM_in_12_samples/DEGs/meningitis_vs_control_FDRq_1.00.tsv",
  sep = "\t", 
  header = TRUE)
```

# Filter by FDRq
```{r}
group_sex_GFAP <- group_sex_GFAP[group_sex_GFAP$adj.P.Val < thresh,]
```

# Up/down-regulated lists
```{r}
group_sex_GFAP_up <- subset(group_sex_GFAP$ID, group_sex_GFAP$logFC > 0)
group_sex_GFAP_down <- subset(group_sex_GFAP$ID, group_sex_GFAP$logFC < 0)

list_input <- list("group_sex_GFAP up-regulated" = group_sex_GFAP_up,
                   "group_sex_GFAP down-regulated" = group_sex_GFAP_down)

data <- fromList(list_input)
```

# Metascape input
```{r}
write.table(x = group_sex_GFAP_up,
            file = paste0("../../results/meninges_1CPM_in_12_samples/",
                          "DEGs/metascape_input_upregulated_FDRq_",
                          format(thresh, nsmall = 2), ".tsv"),
            quote = FALSE,
            row.names = FALSE,
            col.names = FALSE)

write.table(x = group_sex_GFAP_down,
            file = paste0("../../results/meninges_1CPM_in_12_samples/",
                          "DEGs/metascape_input_downregulated_FDRq_",
                          format(thresh, nsmall = 2), ".tsv"),
            quote = FALSE,
            row.names = FALSE,
            col.names = FALSE)
```



